[pytest]
asyncio_mode = auto
python_files = test_*.py
filterwarnings = ignore::DeprecationWarning

markers =
    windows: mark test as Windows-only
    requires_pwsh: test requires pwsh/powershell
    requires_playwright: test requires playwright and browsers

addopts = -q
